sudo: required

services:
  - docker

before_install:
  # - docker build -t test .
  # - docker run -it test curl localhost

script:
  - docker run -d -p 80:80 nginx; sleep 5
  - curl --retry 10 --retry-delay 5 -v http://localhost:80
