sudo: required

services:
  - docker

before_install:
  - docker build -t test .
  - docker run -d -p 80:80 test; sleep 5
  # - docker run -d -p 80:80 nginx; sleep 5

script:
  - curl --retry 10 --retry-delay 5 -v http://localhost:80
